*----------------------------------------------------------------------*
*   INCLUDE ZBYHR_P016_PAK01TRS                                                   *
*----------------------------------------------------------------------*

*___SELECTION SCREEN

*-> SK insertion 18112008
SELECTION-SCREEN BEGIN OF BLOCK ssk WITH FRAME TITLE TEXT-n40.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT (31) TEXT-n41 FOR FIELD p_papaa.
    SELECTION-SCREEN POSITION 33.
    PARAMETERS: p_papaa RADIOBUTTON GROUP gr5.
    SELECTION-SCREEN COMMENT 44(25) TEXT-n42 FOR FIELD p_sskno.
    PARAMETERS: p_sskno RADIOBUTTON GROUP gr5.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK ssk.

*PARAMETERS: p_papaa(1) DEFAULT 'X'  NO-DISPLAY.
*"Personel alt alanına göre
*PARAMETERS: p_sskno(1)  NO-DISPLAY.  "SSK numarasına göre
*PARAMETERS: p_grup(1)  NO-DISPLAY.  "Grup koduna göre
*-> SK insertion 18112008

SELECTION-SCREEN BEGIN OF BLOCK rpr WITH FRAME .

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 5.
    PARAMETERS: hakeden AS CHECKBOX DEFAULT 'X'.
    SELECTION-SCREEN COMMENT 8(20) TEXT-ka1.

    SELECTION-SCREEN POSITION 30.
    PARAMETERS: ozet AS CHECKBOX DEFAULT 'X'.
    SELECTION-SCREEN COMMENT 33(05) TEXT-ka2.

  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK rpr.




SELECTION-SCREEN BEGIN OF BLOCK kidem WITH FRAME TITLE TEXT-kid.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT (32) TEXT-sc1 FOR FIELD potkidem.
    SELECTION-SCREEN POSITION 33.
    PARAMETERS: potkidem RADIOBUTTON GROUP gr1.
    PARAMETERS: pottarih LIKE sy-datum DEFAULT sy-datum.

  SELECTION-SCREEN END OF LINE.



  SELECTION-SCREEN BEGIN OF LINE.
    "SELECTION-SCREEN POSITION 33.
    SELECTION-SCREEN COMMENT (32) TEXT-sc2 FOR FIELD norkidem.
    SELECTION-SCREEN POSITION 33.
    PARAMETERS: norkidem RADIOBUTTON GROUP gr1.
    PARAMETERS: norkitar TYPE ptr_donem DEFAULT sy-datum.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
*    SELECTION-SCREEN POSITION 33.
*    SELECTION-SCREEN COMMENT (32) TEXT-sc9 FOR FIELD emek.
    SELECTION-SCREEN COMMENT (32) TEXT-sc9 FOR FIELD emektar.
    SELECTION-SCREEN POSITION 33.
*    PARAMETERS: emek RADIOBUTTON GROUP gr1.
    PARAMETERS: emektar LIKE sy-datum DEFAULT sy-datum.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN SKIP 1.

  SELECTION-SCREEN BEGIN OF LINE.
    "SELECTION-SCREEN POSITION 33.
    SELECTION-SCREEN COMMENT (31) TEXT-sc3 FOR FIELD p_net.
    PARAMETERS: p_net AS CHECKBOX.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    "SELECTION-SCREEN POSITION 33.
    SELECTION-SCREEN COMMENT (31) TEXT-sc4 FOR FIELD hatadety . "60
    PARAMETERS: hatadety LIKE rpcxxxxx-kr_feld1 DEFAULT space.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN SKIP 1.

* Ekleme yapılacak taner.
  SELECTION-SCREEN BEGIN OF BLOCK gunler WITH FRAME TITLE TEXT-gun.

    SELECTION-SCREEN BEGIN OF LINE.
      "SELECTION-SCREEN POSITION 31.
      SELECTION-SCREEN COMMENT (29) TEXT-sc6 FOR FIELD artikyil.
      PARAMETERS: artikyil LIKE rpcxxxxx-kr_feld1 DEFAULT space.
    SELECTION-SCREEN END OF LINE.


* Bu Parametre işaretlendiğinde çıkış gününü çalışmış olarak
* değerlendirip, normal hesaplamaya +1 gün eklenir.

    SELECTION-SCREEN BEGIN OF LINE.
      "SELECTION-SCREEN POSITION 31.
      SELECTION-SCREEN COMMENT (29) TEXT-s14 FOR FIELD cikisgun.
      PARAMETERS: cikisgun LIKE rpcxxxxx-kr_feld1 DEFAULT space.
    SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN END OF BLOCK gunler.

  SELECTION-SCREEN BEGIN OF BLOCK hesap WITH FRAME TITLE TEXT-hes.

    SELECTION-SCREEN BEGIN OF LINE.
      "SELECTION-SCREEN POSITION 31.
      SELECTION-SCREEN COMMENT (29) TEXT-s10 FOR FIELD hesap.
      PARAMETERS: hesap LIKE rpcxxxxx-kr_feld1 DEFAULT space.
    SELECTION-SCREEN END OF LINE.


    SELECTION-SCREEN BEGIN OF LINE.
      "SELECTION-SCREEN POSITION 31.
      SELECTION-SCREEN COMMENT (29) TEXT-s15 FOR FIELD saat365.
      PARAMETERS: saat365 LIKE rpcxxxxx-kr_feld1 DEFAULT space.
*PARAMETERS: kpklo LIKE P0008-BSGRD DEFAULT space.
    SELECTION-SCREEN END OF LINE.

    SELECTION-SCREEN BEGIN OF LINE.
      "SELECTION-SCREEN POSITION 31.
      SELECTION-SCREEN COMMENT (29) TEXT-s16 MODIF ID kpk FOR FIELD kpklo.
      PARAMETERS: kpklo LIKE rpcxxxxx-kr_feld1 DEFAULT space MODIF ID kpk.
    SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN END OF BLOCK hesap.

  SELECTION-SCREEN BEGIN OF BLOCK rpr2 WITH FRAME .
    SELECTION-SCREEN BEGIN OF LINE.
      PARAMETERS: recalckd AS CHECKBOX.
      SELECTION-SCREEN COMMENT 5(40) TEXT-zc3.
    SELECTION-SCREEN END OF LINE.

    SELECTION-SCREEN BEGIN OF LINE.
      PARAMETERS:  zsonbrd AS CHECKBOX DEFAULT 'X'.
      SELECTION-SCREEN COMMENT 5(60) TEXT-zc0.
    SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN END OF BLOCK rpr2.

  SELECTION-SCREEN BEGIN OF LINE.
    "SELECTION-SCREEN POSITION 33.
    SELECTION-SCREEN COMMENT (31) TEXT-s12 FOR FIELD p_sir.
    PARAMETERS: p_sir AS CHECKBOX.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN SKIP 1.

  SELECTION-SCREEN BEGIN OF LINE.
    "SELECTION-SCREEN POSITION 33.
    SELECTION-SCREEN COMMENT (31) TEXT-sc5 FOR FIELD kidmtest.
    PARAMETERS: kidmtest LIKE rpcxxxxx-kr_feld1 DEFAULT 'X'.
  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK kidem.

PARAMETERS: stand LIKE pc260-srtza DEFAULT 'A' NO-DISPLAY.
*
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN BEGIN OF BLOCK lgart WITH FRAME TITLE TEXT-lgt.

*  PARAMETERS: wty_9chd LIKE t512w-lgart DEFAULT '/CHD'  .
  PARAMETERS: inf41 LIKE p0041-dar01 DEFAULT '03'.
  PARAMETERS: netu LIKE t512t-lgart.
  PARAMETERS: kidu LIKE t512t-lgart.
  SELECT-OPTIONS: wty_ubz FOR t554s-subty NO INTERVALS DEFAULT '0190'.
  SELECTION-SCREEN BEGIN OF LINE.
    "SELECTION-SCREEN POSITION 33.
    SELECTION-SCREEN COMMENT (31) TEXT-s11 FOR FIELD biryil .
    PARAMETERS: biryil LIKE rpcxxxxx-kr_feld1 DEFAULT 'X'.
  SELECTION-SCREEN END OF LINE.


  SELECTION-SCREEN SKIP 1.


  SELECT-OPTIONS: wty_9chd FOR t512w-lgart NO-EXTENSION
                                           NO INTERVALS."EFAULT '2005'.
  SELECT-OPTIONS: wty_prim FOR t512w-lgart DEFAULT '3000' TO  '3001'
  NO-DISPLAY.

*  SELECT-OPTIONS: wty_9ubz FOR t554s-subty NO INTERVALS ."EFAULT '0190'.

  SELECT-OPTIONS: wty_ikrm FOR t512w-lgart NO INTERVALS DEFAULT '/PAY'.

  SELECT-OPTIONS: w_ikrm14 FOR t512w-lgart NO INTERVALS DEFAULT '2050'.

  SELECT-OPTIONS: w_kistel FOR t512w-lgart NO INTERVALS .

SELECTION-SCREEN END OF BLOCK lgart.
