*&---------------------------------------------------------------------*
*& Include          ZBYHR_P002_I003
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK bl1 WITH FRAME TITLE TEXT-000 .
  SELECT-OPTIONS : s_kst01 FOR p0027-kst01 .
  SELECT-OPTIONS : s_fpper FOR s001-spmon
         NO-EXTENSION OBLIGATORY DEFAULT sy-datum.

  SELECTION-SCREEN BEGIN OF LINE .
    SELECTION-SCREEN COMMENT (31) TEXT-901 MODIF ID m01 .
    PARAMETERS     : p_ek1_t  TYPE stext MODIF ID m01.
    PARAMETERS     : p_ek1_u  TYPE betrg MODIF ID m01.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT (31) TEXT-901  MODIF ID m01 .
    PARAMETERS     : p_ek2_t  TYPE stext MODIF ID m01 .
    PARAMETERS     : p_ek2_u  TYPE betrg MODIF ID m01 .
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT (31) TEXT-901  MODIF ID m01 .
    PARAMETERS     : p_ek3_t  TYPE stext MODIF ID m01 .
    PARAMETERS     : p_ek3_u  TYPE betrg MODIF ID m01 .
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT (31) TEXT-901  MODIF ID m01 .
    PARAMETERS     : p_ek4_t  TYPE stext MODIF ID m01 .
    PARAMETERS     : p_ek4_u  TYPE betrg MODIF ID m01 .
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT (31) TEXT-901  MODIF ID m01 .
    PARAMETERS     : p_ek5_t  TYPE stext MODIF ID m01 .
    PARAMETERS     : p_ek5_u  TYPE betrg MODIF ID m01 .
  SELECTION-SCREEN END OF LINE.
  PARAMETERS     : p_srtza TYPE hrcce_srtza DEFAULT 'A' ."NO-DISPLAY.
  PARAMETERS     : pc_27 AS CHECKBOX MODIF ID p27.
  "PARAMETERS     : p_ort   AS CHECKBOX USER-COMMAND cmd1.
  SELECTION-SCREEN PUSHBUTTON /1(24) TEXT-037 USER-COMMAND sort .

  SELECT-OPTIONS : s_fnams FOR  ssort-ftxt NO-DISPLAY.
  PARAMETERS     : p_alv   TYPE char1      NO-DISPLAY.
SELECTION-SCREEN END OF BLOCK bl1.
