*&---------------------------------------------------------------------*
*& Include ZBYHR_P013_TOP
*&---------------------------------------------------------------------*


type-pools: icon.

SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-t00 .

PARAMETERS : p_abkrs TYPE t569v-abkrs OBLIGATORY,
             p_datum type datum OBLIGATORY.
SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE text-t01.
PARAMETERS: p_relas RADIOBUTTON GROUP rb1 DEFAULT 'X',
            p_corre RADIOBUTTON GROUP rb1,
            p_exit RADIOBUTTON GROUP rb1.
SELECTION-SCREEN END OF BLOCK b2.

SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME TITLE text-t02.
 SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(70) lv_abk01.
  SELECTION-SCREEN END OF LINE.
   SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(70) lv_abk02.
  SELECTION-SCREEN END OF LINE.
     SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(70) lv_abk03.
  SELECTION-SCREEN END OF LINE.
     SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(70) lv_abk04.
  SELECTION-SCREEN END OF LINE.
     SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(70) lv_abk05.
  SELECTION-SCREEN END OF LINE.
     SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(70) lv_abk06.
  SELECTION-SCREEN END OF LINE.
     SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(70) lv_abk07.
  SELECTION-SCREEN END OF LINE.
     SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(70) lv_abk08.
  SELECTION-SCREEN END OF LINE.
     SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(70) lv_abk09.
  SELECTION-SCREEN END OF LINE.
     SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(70) lv_abk10.
  SELECTION-SCREEN END OF LINE.
     SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(70) lv_abk11.
  SELECTION-SCREEN END OF LINE.
     SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(70) lv_abk12.
  SELECTION-SCREEN END OF LINE.
     SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(70) lv_abk13.
  SELECTION-SCREEN END OF LINE.
     SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(70) lv_abk14.
  SELECTION-SCREEN END OF LINE.
"     SELECTION-SCREEN BEGIN OF LINE.
"SELECTION-SCREEN COMMENT 1(70) lv_abk15.
"  SELECTION-SCREEN END OF LINE.
"     SELECTION-SCREEN BEGIN OF LINE.
"SELECTION-SCREEN COMMENT 1(70) lv_abk16.
"  SELECTION-SCREEN END OF LINE.
"     SELECTION-SCREEN BEGIN OF LINE.
"SELECTION-SCREEN COMMENT 1(70) lv_abk17.
"  SELECTION-SCREEN END OF LINE.
"     SELECTION-SCREEN BEGIN OF LINE.
"SELECTION-SCREEN COMMENT 1(70) lv_abk18.
"  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b3.
