*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZBYHR_V001......................................*
FORM GET_DATA_ZBYHR_V001.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZBYHR_T001 WHERE
(VIM_WHERETAB) .
    CLEAR ZBYHR_V001 .
ZBYHR_V001-MANDT =
ZBYHR_T001-MANDT .
ZBYHR_V001-BUKRS =
ZBYHR_T001-BUKRS .
ZBYHR_V001-WERKS =
ZBYHR_T001-WERKS .
ZBYHR_V001-BTRTL =
ZBYHR_T001-BTRTL .
ZBYHR_V001-IBAN =
ZBYHR_T001-IBAN .
ZBYHR_V001-KURKOD =
ZBYHR_T001-KURKOD .
ZBYHR_V001-SUBKOD =
ZBYHR_T001-SUBKOD .
ZBYHR_V001-HSPNO =
ZBYHR_T001-HSPNO .
ZBYHR_V001-FTYPE =
ZBYHR_T001-FTYPE .
    SELECT SINGLE * FROM T001 WHERE
BUKRS = ZBYHR_T001-BUKRS .
    IF SY-SUBRC EQ 0.
ZBYHR_V001-BUTXT =
T001-BUTXT .
    ENDIF.
<VIM_TOTAL_STRUC> = ZBYHR_V001.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZBYHR_V001 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZBYHR_V001.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZBYHR_V001-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T001 WHERE
  BUKRS = ZBYHR_V001-BUKRS AND
  WERKS = ZBYHR_V001-WERKS AND
  BTRTL = ZBYHR_V001-BTRTL .
    IF SY-SUBRC = 0.
    DELETE ZBYHR_T001 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T001 WHERE
  BUKRS = ZBYHR_V001-BUKRS AND
  WERKS = ZBYHR_V001-WERKS AND
  BTRTL = ZBYHR_V001-BTRTL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZBYHR_T001.
    ENDIF.
ZBYHR_T001-MANDT =
ZBYHR_V001-MANDT .
ZBYHR_T001-BUKRS =
ZBYHR_V001-BUKRS .
ZBYHR_T001-WERKS =
ZBYHR_V001-WERKS .
ZBYHR_T001-BTRTL =
ZBYHR_V001-BTRTL .
ZBYHR_T001-IBAN =
ZBYHR_V001-IBAN .
ZBYHR_T001-KURKOD =
ZBYHR_V001-KURKOD .
ZBYHR_T001-SUBKOD =
ZBYHR_V001-SUBKOD .
ZBYHR_T001-HSPNO =
ZBYHR_V001-HSPNO .
ZBYHR_T001-FTYPE =
ZBYHR_V001-FTYPE .
    IF SY-SUBRC = 0.
    UPDATE ZBYHR_T001 ##WARN_OK.
    ELSE.
    INSERT ZBYHR_T001 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZBYHR_V001-UPD_FLAG,
STATUS_ZBYHR_V001-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZBYHR_V001.
  SELECT SINGLE * FROM ZBYHR_T001 WHERE
BUKRS = ZBYHR_V001-BUKRS AND
WERKS = ZBYHR_V001-WERKS AND
BTRTL = ZBYHR_V001-BTRTL .
ZBYHR_V001-MANDT =
ZBYHR_T001-MANDT .
ZBYHR_V001-BUKRS =
ZBYHR_T001-BUKRS .
ZBYHR_V001-WERKS =
ZBYHR_T001-WERKS .
ZBYHR_V001-BTRTL =
ZBYHR_T001-BTRTL .
ZBYHR_V001-IBAN =
ZBYHR_T001-IBAN .
ZBYHR_V001-KURKOD =
ZBYHR_T001-KURKOD .
ZBYHR_V001-SUBKOD =
ZBYHR_T001-SUBKOD .
ZBYHR_V001-HSPNO =
ZBYHR_T001-HSPNO .
ZBYHR_V001-FTYPE =
ZBYHR_T001-FTYPE .
    SELECT SINGLE * FROM T001 WHERE
BUKRS = ZBYHR_T001-BUKRS .
    IF SY-SUBRC EQ 0.
ZBYHR_V001-BUTXT =
T001-BUTXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V001-BUTXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZBYHR_V001 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZBYHR_V001-BUKRS TO
ZBYHR_T001-BUKRS .
MOVE ZBYHR_V001-WERKS TO
ZBYHR_T001-WERKS .
MOVE ZBYHR_V001-BTRTL TO
ZBYHR_T001-BTRTL .
MOVE ZBYHR_V001-MANDT TO
ZBYHR_T001-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZBYHR_T001'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZBYHR_T001 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZBYHR_T001'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZBYHR_V001 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZBYHR_T001-MANDT =
ZBYHR_V001-MANDT .
ZBYHR_T001-BUKRS =
ZBYHR_V001-BUKRS .
ZBYHR_T001-WERKS =
ZBYHR_V001-WERKS .
ZBYHR_T001-BTRTL =
ZBYHR_V001-BTRTL .
ZBYHR_T001-IBAN =
ZBYHR_V001-IBAN .
ZBYHR_T001-KURKOD =
ZBYHR_V001-KURKOD .
ZBYHR_T001-SUBKOD =
ZBYHR_V001-SUBKOD .
ZBYHR_T001-HSPNO =
ZBYHR_V001-HSPNO .
ZBYHR_T001-FTYPE =
ZBYHR_V001-FTYPE .
    SELECT SINGLE * FROM T001 WHERE
BUKRS = ZBYHR_T001-BUKRS .
    IF SY-SUBRC EQ 0.
ZBYHR_V001-BUTXT =
T001-BUTXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V001-BUTXT .
    ENDIF.
ENDFORM.
*...processing: ZBYHR_V002......................................*
FORM GET_DATA_ZBYHR_V002.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZBYHR_T002 WHERE
(VIM_WHERETAB) .
    CLEAR ZBYHR_V002 .
ZBYHR_V002-MANDT =
ZBYHR_T002-MANDT .
ZBYHR_V002-TCODE =
ZBYHR_T002-TCODE .
ZBYHR_V002-BUKRS =
ZBYHR_T002-BUKRS .
ZBYHR_V002-PNAME =
ZBYHR_T002-PNAME .
ZBYHR_V002-PFILE =
ZBYHR_T002-PFILE .
ZBYHR_V002-WERKS =
ZBYHR_T002-WERKS .
ZBYHR_V002-BTRTL =
ZBYHR_T002-BTRTL .
    SELECT SINGLE * FROM ZBYHR_T001 WHERE
BUKRS = ZBYHR_T002-BUKRS AND
WERKS = ZBYHR_T002-WERKS AND
BTRTL = ZBYHR_T002-BTRTL .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T001 WHERE
BUKRS = ZBYHR_T001-BUKRS .
      IF SY-SUBRC EQ 0.
ZBYHR_V002-BUTXT =
T001-BUTXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZBYHR_V002.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZBYHR_V002 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZBYHR_V002.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZBYHR_V002-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T002 WHERE
  TCODE = ZBYHR_V002-TCODE AND
  BUKRS = ZBYHR_V002-BUKRS AND
  WERKS = ZBYHR_V002-WERKS AND
  BTRTL = ZBYHR_V002-BTRTL .
    IF SY-SUBRC = 0.
    DELETE ZBYHR_T002 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T002 WHERE
  TCODE = ZBYHR_V002-TCODE AND
  BUKRS = ZBYHR_V002-BUKRS AND
  WERKS = ZBYHR_V002-WERKS AND
  BTRTL = ZBYHR_V002-BTRTL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZBYHR_T002.
    ENDIF.
ZBYHR_T002-MANDT =
ZBYHR_V002-MANDT .
ZBYHR_T002-TCODE =
ZBYHR_V002-TCODE .
ZBYHR_T002-BUKRS =
ZBYHR_V002-BUKRS .
ZBYHR_T002-PNAME =
ZBYHR_V002-PNAME .
ZBYHR_T002-PFILE =
ZBYHR_V002-PFILE .
ZBYHR_T002-WERKS =
ZBYHR_V002-WERKS .
ZBYHR_T002-BTRTL =
ZBYHR_V002-BTRTL .
    IF SY-SUBRC = 0.
    UPDATE ZBYHR_T002 ##WARN_OK.
    ELSE.
    INSERT ZBYHR_T002 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZBYHR_V002-UPD_FLAG,
STATUS_ZBYHR_V002-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZBYHR_V002.
  SELECT SINGLE * FROM ZBYHR_T002 WHERE
TCODE = ZBYHR_V002-TCODE AND
BUKRS = ZBYHR_V002-BUKRS AND
WERKS = ZBYHR_V002-WERKS AND
BTRTL = ZBYHR_V002-BTRTL .
ZBYHR_V002-MANDT =
ZBYHR_T002-MANDT .
ZBYHR_V002-TCODE =
ZBYHR_T002-TCODE .
ZBYHR_V002-BUKRS =
ZBYHR_T002-BUKRS .
ZBYHR_V002-PNAME =
ZBYHR_T002-PNAME .
ZBYHR_V002-PFILE =
ZBYHR_T002-PFILE .
ZBYHR_V002-WERKS =
ZBYHR_T002-WERKS .
ZBYHR_V002-BTRTL =
ZBYHR_T002-BTRTL .
    SELECT SINGLE * FROM ZBYHR_T001 WHERE
BUKRS = ZBYHR_T002-BUKRS AND
WERKS = ZBYHR_T002-WERKS AND
BTRTL = ZBYHR_T002-BTRTL .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T001 WHERE
BUKRS = ZBYHR_T001-BUKRS .
      IF SY-SUBRC EQ 0.
ZBYHR_V002-BUTXT =
T001-BUTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZBYHR_V002-BUTXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V002-BUTXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZBYHR_V002 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZBYHR_V002-TCODE TO
ZBYHR_T002-TCODE .
MOVE ZBYHR_V002-BUKRS TO
ZBYHR_T002-BUKRS .
MOVE ZBYHR_V002-WERKS TO
ZBYHR_T002-WERKS .
MOVE ZBYHR_V002-BTRTL TO
ZBYHR_T002-BTRTL .
MOVE ZBYHR_V002-MANDT TO
ZBYHR_T002-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZBYHR_T002'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZBYHR_T002 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZBYHR_T002'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZBYHR_V002 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZBYHR_T002-MANDT =
ZBYHR_V002-MANDT .
ZBYHR_T002-TCODE =
ZBYHR_V002-TCODE .
ZBYHR_T002-BUKRS =
ZBYHR_V002-BUKRS .
ZBYHR_T002-PNAME =
ZBYHR_V002-PNAME .
ZBYHR_T002-PFILE =
ZBYHR_V002-PFILE .
ZBYHR_T002-WERKS =
ZBYHR_V002-WERKS .
ZBYHR_T002-BTRTL =
ZBYHR_V002-BTRTL .
    SELECT SINGLE * FROM ZBYHR_T001 WHERE
BUKRS = ZBYHR_T002-BUKRS AND
WERKS = ZBYHR_T002-WERKS AND
BTRTL = ZBYHR_T002-BTRTL .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T001 WHERE
BUKRS = ZBYHR_T001-BUKRS .
      IF SY-SUBRC EQ 0.
ZBYHR_V002-BUTXT =
T001-BUTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZBYHR_V002-BUTXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V002-BUTXT .
    ENDIF.
ENDFORM.

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
