PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBYHR_V027 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBYHR_V027-PERNR .
    FIELD ZBYHR_V027-ENAME .
    FIELD ZBYHR_V027-AWART .
    FIELD ZBYHR_V027-ATEXT .
    FIELD ZBYHR_V027-BEGDA .
    FIELD ZBYHR_V027-ENDDA .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZBYHR_V027 ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBYHR_V027-PERNR .
    FIELD ZBYHR_V027-AWART .
    FIELD ZBYHR_V027-BEGDA .
    FIELD ZBYHR_V027-ENDDA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
