*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZBYHR_V027......................................*
FORM GET_DATA_ZBYHR_V027.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZBYHR_T027 WHERE
(VIM_WHERETAB) .
    CLEAR ZBYHR_V027 .
ZBYHR_V027-MANDT =
ZBYHR_T027-MANDT .
ZBYHR_V027-PERNR =
ZBYHR_T027-PERNR .
ZBYHR_V027-AWART =
ZBYHR_T027-AWART .
ZBYHR_V027-BEGDA =
ZBYHR_T027-BEGDA .
ZBYHR_V027-ENDDA =
ZBYHR_T027-ENDDA .
    SELECT * FROM PA0001 WHERE
PERNR = ZBYHR_T027-PERNR .
ZBYHR_V027-ENAME =
PA0001-ENAME .
      EXIT.
    ENDSELECT.
    SELECT * FROM T554S WHERE
MOABW = '01' AND
SUBTY = ZBYHR_T027-AWART .
      SELECT SINGLE * FROM T554T WHERE
MOABW = T554S-MOABW AND
AWART = T554S-SUBTY AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZBYHR_V027-ATEXT =
T554T-ATEXT .
      ENDIF.
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = ZBYHR_V027.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZBYHR_V027 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZBYHR_V027.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZBYHR_V027-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T027 WHERE
  PERNR = ZBYHR_V027-PERNR AND
  AWART = ZBYHR_V027-AWART AND
  BEGDA = ZBYHR_V027-BEGDA AND
  ENDDA = ZBYHR_V027-ENDDA .
    IF SY-SUBRC = 0.
    DELETE ZBYHR_T027 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T027 WHERE
  PERNR = ZBYHR_V027-PERNR AND
  AWART = ZBYHR_V027-AWART AND
  BEGDA = ZBYHR_V027-BEGDA AND
  ENDDA = ZBYHR_V027-ENDDA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZBYHR_T027.
    ENDIF.
ZBYHR_T027-MANDT =
ZBYHR_V027-MANDT .
ZBYHR_T027-PERNR =
ZBYHR_V027-PERNR .
ZBYHR_T027-AWART =
ZBYHR_V027-AWART .
ZBYHR_T027-BEGDA =
ZBYHR_V027-BEGDA .
ZBYHR_T027-ENDDA =
ZBYHR_V027-ENDDA .
    IF SY-SUBRC = 0.
    UPDATE ZBYHR_T027 ##WARN_OK.
    ELSE.
    INSERT ZBYHR_T027 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZBYHR_V027-UPD_FLAG,
STATUS_ZBYHR_V027-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZBYHR_V027.
  SELECT SINGLE * FROM ZBYHR_T027 WHERE
PERNR = ZBYHR_V027-PERNR AND
AWART = ZBYHR_V027-AWART AND
BEGDA = ZBYHR_V027-BEGDA AND
ENDDA = ZBYHR_V027-ENDDA .
ZBYHR_V027-MANDT =
ZBYHR_T027-MANDT .
ZBYHR_V027-PERNR =
ZBYHR_T027-PERNR .
ZBYHR_V027-AWART =
ZBYHR_T027-AWART .
ZBYHR_V027-BEGDA =
ZBYHR_T027-BEGDA .
ZBYHR_V027-ENDDA =
ZBYHR_T027-ENDDA .
    SELECT * FROM PA0001 WHERE
PERNR = ZBYHR_T027-PERNR .
ZBYHR_V027-ENAME =
PA0001-ENAME .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V027-ENAME .
    ENDIF.
    SELECT * FROM T554S WHERE
MOABW = '01' AND
SUBTY = ZBYHR_T027-AWART .
      SELECT SINGLE * FROM T554T WHERE
MOABW = T554S-MOABW AND
AWART = T554S-SUBTY AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZBYHR_V027-ATEXT =
T554T-ATEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZBYHR_V027-ATEXT .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V027-ATEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZBYHR_V027 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZBYHR_V027-PERNR TO
ZBYHR_T027-PERNR .
MOVE ZBYHR_V027-AWART TO
ZBYHR_T027-AWART .
MOVE ZBYHR_V027-BEGDA TO
ZBYHR_T027-BEGDA .
MOVE ZBYHR_V027-ENDDA TO
ZBYHR_T027-ENDDA .
MOVE ZBYHR_V027-MANDT TO
ZBYHR_T027-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZBYHR_T027'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZBYHR_T027 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZBYHR_T027'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZBYHR_V027 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZBYHR_T027-MANDT =
ZBYHR_V027-MANDT .
ZBYHR_T027-PERNR =
ZBYHR_V027-PERNR .
ZBYHR_T027-AWART =
ZBYHR_V027-AWART .
ZBYHR_T027-BEGDA =
ZBYHR_V027-BEGDA .
ZBYHR_T027-ENDDA =
ZBYHR_V027-ENDDA .
    SELECT * FROM PA0001 WHERE
PERNR = ZBYHR_T027-PERNR .
ZBYHR_V027-ENAME =
PA0001-ENAME .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V027-ENAME .
    ENDIF.
    SELECT * FROM T554S WHERE
MOABW = '01' AND
SUBTY = ZBYHR_T027-AWART .
      SELECT SINGLE * FROM T554T WHERE
MOABW = T554S-MOABW AND
AWART = T554S-SUBTY AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZBYHR_V027-ATEXT =
T554T-ATEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZBYHR_V027-ATEXT .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V027-ATEXT .
    ENDIF.
ENDFORM.
