PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBYHR_T004 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBYHR_T004-PROGNAME .
    FIELD ZBYHR_T004-BUKRS .
    FIELD ZBYHR_T004-T_LGART .
    FIELD ZBYHR_T004-S_LGART .
    FIELD ZBYHR_T004-AMT_MUL .
    FIELD ZBYHR_T004-AMT_DIV .
    FIELD ZBYHR_T004-NUM_MUL .
    FIELD ZBYHR_T004-NUM_DIV .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBYHR_T004-PROGNAME .
    FIELD ZBYHR_T004-BUKRS .
    FIELD ZBYHR_T004-T_LGART .
    FIELD ZBYHR_T004-S_LGART .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
