PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBYHR_V001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBYHR_V001-BUKRS .
    FIELD ZBYHR_V001-BUTXT .
    FIELD ZBYHR_V001-WERKS .
    FIELD ZBYHR_V001-BTRTL .
    FIELD ZBYHR_V001-IBAN .
    FIELD ZBYHR_V001-KURKOD .
    FIELD ZBYHR_V001-SUBKOD .
    FIELD ZBYHR_V001-HSPNO .
    FIELD ZBYHR_V001-FTYPE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZBYHR_V001 ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBYHR_V001-BUKRS .
    FIELD ZBYHR_V001-WERKS .
    FIELD ZBYHR_V001-BTRTL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
