*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZBYHR_V012......................................*
FORM GET_DATA_ZBYHR_V012.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZBYHR_T012 WHERE
(VIM_WHERETAB) .
    CLEAR ZBYHR_V012 .
ZBYHR_V012-MANDT =
ZBYHR_T012-MANDT .
ZBYHR_V012-SEQNO =
ZBYHR_T012-SEQNO .
ZBYHR_V012-ANAGR =
ZBYHR_T012-ANAGR .
ZBYHR_V012-DESCR =
ZBYHR_T012-DESCR .
<VIM_TOTAL_STRUC> = ZBYHR_V012.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZBYHR_V012 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZBYHR_V012.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZBYHR_V012-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T012 WHERE
  SEQNO = ZBYHR_V012-SEQNO AND
  ANAGR = ZBYHR_V012-ANAGR .
    IF SY-SUBRC = 0.
    DELETE ZBYHR_T012 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T012 WHERE
  SEQNO = ZBYHR_V012-SEQNO AND
  ANAGR = ZBYHR_V012-ANAGR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZBYHR_T012.
    ENDIF.
ZBYHR_T012-MANDT =
ZBYHR_V012-MANDT .
ZBYHR_T012-SEQNO =
ZBYHR_V012-SEQNO .
ZBYHR_T012-ANAGR =
ZBYHR_V012-ANAGR .
ZBYHR_T012-DESCR =
ZBYHR_V012-DESCR .
    IF SY-SUBRC = 0.
    UPDATE ZBYHR_T012 ##WARN_OK.
    ELSE.
    INSERT ZBYHR_T012 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZBYHR_V012-UPD_FLAG,
STATUS_ZBYHR_V012-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZBYHR_V012.
  SELECT SINGLE * FROM ZBYHR_T012 WHERE
SEQNO = ZBYHR_V012-SEQNO AND
ANAGR = ZBYHR_V012-ANAGR .
ZBYHR_V012-MANDT =
ZBYHR_T012-MANDT .
ZBYHR_V012-SEQNO =
ZBYHR_T012-SEQNO .
ZBYHR_V012-ANAGR =
ZBYHR_T012-ANAGR .
ZBYHR_V012-DESCR =
ZBYHR_T012-DESCR .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZBYHR_V012 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZBYHR_V012-SEQNO TO
ZBYHR_T012-SEQNO .
MOVE ZBYHR_V012-ANAGR TO
ZBYHR_T012-ANAGR .
MOVE ZBYHR_V012-MANDT TO
ZBYHR_T012-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZBYHR_T012'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZBYHR_T012 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZBYHR_T012'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZBYHR_V013......................................*
FORM GET_DATA_ZBYHR_V013.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZBYHR_T013 WHERE
(VIM_WHERETAB) .
    CLEAR ZBYHR_V013 .
ZBYHR_V013-MANDT =
ZBYHR_T013-MANDT .
ZBYHR_V013-SEQNO =
ZBYHR_T013-SEQNO .
ZBYHR_V013-ANAGR =
ZBYHR_T013-ANAGR .
ZBYHR_V013-ALTGR =
ZBYHR_T013-ALTGR .
ZBYHR_V013-DESCR =
ZBYHR_T013-DESCR .
    SELECT SINGLE * FROM ZBYHR_T012 WHERE
SEQNO = ZBYHR_T013-SEQNO AND
ANAGR = ZBYHR_T013-ANAGR .
    IF SY-SUBRC EQ 0.
ZBYHR_V013-ANAGR_T =
ZBYHR_T012-DESCR .
    ENDIF.
<VIM_TOTAL_STRUC> = ZBYHR_V013.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZBYHR_V013 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZBYHR_V013.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZBYHR_V013-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T013 WHERE
  SEQNO = ZBYHR_V013-SEQNO AND
  ANAGR = ZBYHR_V013-ANAGR AND
  ALTGR = ZBYHR_V013-ALTGR .
    IF SY-SUBRC = 0.
    DELETE ZBYHR_T013 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T013 WHERE
  SEQNO = ZBYHR_V013-SEQNO AND
  ANAGR = ZBYHR_V013-ANAGR AND
  ALTGR = ZBYHR_V013-ALTGR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZBYHR_T013.
    ENDIF.
ZBYHR_T013-MANDT =
ZBYHR_V013-MANDT .
ZBYHR_T013-SEQNO =
ZBYHR_V013-SEQNO .
ZBYHR_T013-ANAGR =
ZBYHR_V013-ANAGR .
ZBYHR_T013-ALTGR =
ZBYHR_V013-ALTGR .
ZBYHR_T013-DESCR =
ZBYHR_V013-DESCR .
    IF SY-SUBRC = 0.
    UPDATE ZBYHR_T013 ##WARN_OK.
    ELSE.
    INSERT ZBYHR_T013 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZBYHR_V013-UPD_FLAG,
STATUS_ZBYHR_V013-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZBYHR_V013.
  SELECT SINGLE * FROM ZBYHR_T013 WHERE
SEQNO = ZBYHR_V013-SEQNO AND
ANAGR = ZBYHR_V013-ANAGR AND
ALTGR = ZBYHR_V013-ALTGR .
ZBYHR_V013-MANDT =
ZBYHR_T013-MANDT .
ZBYHR_V013-SEQNO =
ZBYHR_T013-SEQNO .
ZBYHR_V013-ANAGR =
ZBYHR_T013-ANAGR .
ZBYHR_V013-ALTGR =
ZBYHR_T013-ALTGR .
ZBYHR_V013-DESCR =
ZBYHR_T013-DESCR .
    SELECT SINGLE * FROM ZBYHR_T012 WHERE
SEQNO = ZBYHR_T013-SEQNO AND
ANAGR = ZBYHR_T013-ANAGR .
    IF SY-SUBRC EQ 0.
ZBYHR_V013-ANAGR_T =
ZBYHR_T012-DESCR .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V013-ANAGR_T .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZBYHR_V013 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZBYHR_V013-SEQNO TO
ZBYHR_T013-SEQNO .
MOVE ZBYHR_V013-ANAGR TO
ZBYHR_T013-ANAGR .
MOVE ZBYHR_V013-ALTGR TO
ZBYHR_T013-ALTGR .
MOVE ZBYHR_V013-MANDT TO
ZBYHR_T013-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZBYHR_T013'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZBYHR_T013 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZBYHR_T013'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZBYHR_V013 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZBYHR_T013-MANDT =
ZBYHR_V013-MANDT .
ZBYHR_T013-SEQNO =
ZBYHR_V013-SEQNO .
ZBYHR_T013-ANAGR =
ZBYHR_V013-ANAGR .
ZBYHR_T013-ALTGR =
ZBYHR_V013-ALTGR .
ZBYHR_T013-DESCR =
ZBYHR_V013-DESCR .
    SELECT SINGLE * FROM ZBYHR_T012 WHERE
SEQNO = ZBYHR_T013-SEQNO AND
ANAGR = ZBYHR_T013-ANAGR .
    IF SY-SUBRC EQ 0.
ZBYHR_V013-ANAGR_T =
ZBYHR_T012-DESCR .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V013-ANAGR_T .
    ENDIF.
ENDFORM.
*...processing: ZBYHR_V014......................................*
FORM GET_DATA_ZBYHR_V014.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZBYHR_T014 WHERE
(VIM_WHERETAB) .
    CLEAR ZBYHR_V014 .
ZBYHR_V014-MANDT =
ZBYHR_T014-MANDT .
ZBYHR_V014-SEQNO =
ZBYHR_T014-SEQNO .
ZBYHR_V014-ANAGR =
ZBYHR_T014-ANAGR .
ZBYHR_V014-ALTGR =
ZBYHR_T014-ALTGR .
ZBYHR_V014-SLGA =
ZBYHR_T014-SLGA .
ZBYHR_V014-LGTXT =
ZBYHR_T014-LGTXT .
ZBYHR_V014-SIRAN =
ZBYHR_T014-SIRAN .
ZBYHR_V014-PDATE =
ZBYHR_T014-PDATE .
ZBYHR_V014-PHOUR =
ZBYHR_T014-PHOUR .
ZBYHR_V014-SUMWT =
ZBYHR_T014-SUMWT .
ZBYHR_V014-PERSON =
ZBYHR_T014-PERSON .
ZBYHR_V014-MILGRT =
ZBYHR_T014-MILGRT .
ZBYHR_V014-DDNTK =
ZBYHR_T014-DDNTK .
    SELECT SINGLE * FROM ZBYHR_T013 WHERE
SEQNO = ZBYHR_T014-SEQNO AND
ANAGR = ZBYHR_T014-ANAGR AND
ALTGR = ZBYHR_T014-ALTGR .
    IF SY-SUBRC EQ 0.
ZBYHR_V014-ALTGR_T =
ZBYHR_T013-DESCR .
      SELECT SINGLE * FROM ZBYHR_T012 WHERE
SEQNO = ZBYHR_T013-SEQNO AND
ANAGR = ZBYHR_T013-ANAGR .
      IF SY-SUBRC EQ 0.
ZBYHR_V014-ANAGR_T =
ZBYHR_T012-DESCR .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZBYHR_V014.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZBYHR_V014 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZBYHR_V014.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZBYHR_V014-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T014 WHERE
  SEQNO = ZBYHR_V014-SEQNO AND
  ANAGR = ZBYHR_V014-ANAGR AND
  ALTGR = ZBYHR_V014-ALTGR AND
  SLGA = ZBYHR_V014-SLGA .
    IF SY-SUBRC = 0.
    DELETE ZBYHR_T014 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T014 WHERE
  SEQNO = ZBYHR_V014-SEQNO AND
  ANAGR = ZBYHR_V014-ANAGR AND
  ALTGR = ZBYHR_V014-ALTGR AND
  SLGA = ZBYHR_V014-SLGA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZBYHR_T014.
    ENDIF.
ZBYHR_T014-MANDT =
ZBYHR_V014-MANDT .
ZBYHR_T014-SEQNO =
ZBYHR_V014-SEQNO .
ZBYHR_T014-ANAGR =
ZBYHR_V014-ANAGR .
ZBYHR_T014-ALTGR =
ZBYHR_V014-ALTGR .
ZBYHR_T014-SLGA =
ZBYHR_V014-SLGA .
ZBYHR_T014-LGTXT =
ZBYHR_V014-LGTXT .
ZBYHR_T014-SIRAN =
ZBYHR_V014-SIRAN .
ZBYHR_T014-PDATE =
ZBYHR_V014-PDATE .
ZBYHR_T014-PHOUR =
ZBYHR_V014-PHOUR .
ZBYHR_T014-SUMWT =
ZBYHR_V014-SUMWT .
ZBYHR_T014-PERSON =
ZBYHR_V014-PERSON .
ZBYHR_T014-MILGRT =
ZBYHR_V014-MILGRT .
ZBYHR_T014-DDNTK =
ZBYHR_V014-DDNTK .
    IF SY-SUBRC = 0.
    UPDATE ZBYHR_T014 ##WARN_OK.
    ELSE.
    INSERT ZBYHR_T014 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZBYHR_V014-UPD_FLAG,
STATUS_ZBYHR_V014-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZBYHR_V014.
  SELECT SINGLE * FROM ZBYHR_T014 WHERE
SEQNO = ZBYHR_V014-SEQNO AND
ANAGR = ZBYHR_V014-ANAGR AND
ALTGR = ZBYHR_V014-ALTGR AND
SLGA = ZBYHR_V014-SLGA .
ZBYHR_V014-MANDT =
ZBYHR_T014-MANDT .
ZBYHR_V014-SEQNO =
ZBYHR_T014-SEQNO .
ZBYHR_V014-ANAGR =
ZBYHR_T014-ANAGR .
ZBYHR_V014-ALTGR =
ZBYHR_T014-ALTGR .
ZBYHR_V014-SLGA =
ZBYHR_T014-SLGA .
ZBYHR_V014-LGTXT =
ZBYHR_T014-LGTXT .
ZBYHR_V014-SIRAN =
ZBYHR_T014-SIRAN .
ZBYHR_V014-PDATE =
ZBYHR_T014-PDATE .
ZBYHR_V014-PHOUR =
ZBYHR_T014-PHOUR .
ZBYHR_V014-SUMWT =
ZBYHR_T014-SUMWT .
ZBYHR_V014-PERSON =
ZBYHR_T014-PERSON .
ZBYHR_V014-MILGRT =
ZBYHR_T014-MILGRT .
ZBYHR_V014-DDNTK =
ZBYHR_T014-DDNTK .
    SELECT SINGLE * FROM ZBYHR_T013 WHERE
SEQNO = ZBYHR_T014-SEQNO AND
ANAGR = ZBYHR_T014-ANAGR AND
ALTGR = ZBYHR_T014-ALTGR .
    IF SY-SUBRC EQ 0.
ZBYHR_V014-ALTGR_T =
ZBYHR_T013-DESCR .
      SELECT SINGLE * FROM ZBYHR_T012 WHERE
SEQNO = ZBYHR_T013-SEQNO AND
ANAGR = ZBYHR_T013-ANAGR .
      IF SY-SUBRC EQ 0.
ZBYHR_V014-ANAGR_T =
ZBYHR_T012-DESCR .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZBYHR_V014-ANAGR_T .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V014-ALTGR_T .
      CLEAR ZBYHR_V014-ANAGR_T .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZBYHR_V014 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZBYHR_V014-SEQNO TO
ZBYHR_T014-SEQNO .
MOVE ZBYHR_V014-ANAGR TO
ZBYHR_T014-ANAGR .
MOVE ZBYHR_V014-ALTGR TO
ZBYHR_T014-ALTGR .
MOVE ZBYHR_V014-SLGA TO
ZBYHR_T014-SLGA .
MOVE ZBYHR_V014-MANDT TO
ZBYHR_T014-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZBYHR_T014'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZBYHR_T014 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZBYHR_T014'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZBYHR_V014 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZBYHR_T014-MANDT =
ZBYHR_V014-MANDT .
ZBYHR_T014-SEQNO =
ZBYHR_V014-SEQNO .
ZBYHR_T014-ANAGR =
ZBYHR_V014-ANAGR .
ZBYHR_T014-ALTGR =
ZBYHR_V014-ALTGR .
ZBYHR_T014-SLGA =
ZBYHR_V014-SLGA .
ZBYHR_T014-LGTXT =
ZBYHR_V014-LGTXT .
ZBYHR_T014-SIRAN =
ZBYHR_V014-SIRAN .
ZBYHR_T014-PDATE =
ZBYHR_V014-PDATE .
ZBYHR_T014-PHOUR =
ZBYHR_V014-PHOUR .
ZBYHR_T014-SUMWT =
ZBYHR_V014-SUMWT .
ZBYHR_T014-PERSON =
ZBYHR_V014-PERSON .
ZBYHR_T014-MILGRT =
ZBYHR_V014-MILGRT .
ZBYHR_T014-DDNTK =
ZBYHR_V014-DDNTK .
    SELECT SINGLE * FROM ZBYHR_T013 WHERE
SEQNO = ZBYHR_T014-SEQNO AND
ANAGR = ZBYHR_T014-ANAGR AND
ALTGR = ZBYHR_T014-ALTGR .
    IF SY-SUBRC EQ 0.
ZBYHR_V014-ALTGR_T =
ZBYHR_T013-DESCR .
      SELECT SINGLE * FROM ZBYHR_T012 WHERE
SEQNO = ZBYHR_T013-SEQNO AND
ANAGR = ZBYHR_T013-ANAGR .
      IF SY-SUBRC EQ 0.
ZBYHR_V014-ANAGR_T =
ZBYHR_T012-DESCR .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZBYHR_V014-ANAGR_T .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V014-ALTGR_T .
      CLEAR ZBYHR_V014-ANAGR_T .
    ENDIF.
ENDFORM.
*...processing: ZBYHR_V015......................................*
FORM GET_DATA_ZBYHR_V015.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZBYHR_T015 WHERE
(VIM_WHERETAB) .
    CLEAR ZBYHR_V015 .
ZBYHR_V015-MANDT =
ZBYHR_T015-MANDT .
ZBYHR_V015-SEQNO =
ZBYHR_T015-SEQNO .
ZBYHR_V015-ANAGR =
ZBYHR_T015-ANAGR .
ZBYHR_V015-ALTGR =
ZBYHR_T015-ALTGR .
ZBYHR_V015-SLGA =
ZBYHR_T015-SLGA .
ZBYHR_V015-LGART =
ZBYHR_T015-LGART .
ZBYHR_V015-PERSK =
ZBYHR_T015-PERSK .
ZBYHR_V015-SSGRP =
ZBYHR_T015-SSGRP .
ZBYHR_V015-SIRAN =
ZBYHR_T015-SIRAN .
ZBYHR_V015-DESCR =
ZBYHR_T015-DESCR .
ZBYHR_V015-PDATE =
ZBYHR_T015-PDATE .
ZBYHR_V015-PHOUR =
ZBYHR_T015-PHOUR .
ZBYHR_V015-SUMWT =
ZBYHR_T015-SUMWT .
ZBYHR_V015-PERSON =
ZBYHR_T015-PERSON .
    SELECT SINGLE * FROM ZBYHR_T014 WHERE
SEQNO = ZBYHR_T015-SEQNO AND
ANAGR = ZBYHR_T015-ANAGR AND
ALTGR = ZBYHR_T015-ALTGR AND
SLGA = ZBYHR_T015-SLGA .
    IF SY-SUBRC EQ 0.
ZBYHR_V015-SLGA_T =
ZBYHR_T014-LGTXT .
      SELECT SINGLE * FROM ZBYHR_T013 WHERE
SEQNO = ZBYHR_T014-SEQNO AND
ANAGR = ZBYHR_T014-ANAGR AND
ALTGR = ZBYHR_T014-ALTGR .
      IF SY-SUBRC EQ 0.
ZBYHR_V015-ALTGR_T =
ZBYHR_T013-DESCR .
        SELECT SINGLE * FROM ZBYHR_T012 WHERE
SEQNO = ZBYHR_T013-SEQNO AND
ANAGR = ZBYHR_T013-ANAGR .
        IF SY-SUBRC EQ 0.
ZBYHR_V015-ANAGR_T =
ZBYHR_T012-DESCR .
        ENDIF.
      ENDIF.
    ENDIF.
    SELECT * FROM T512W WHERE
MOLGA = '47' AND
LGART = ZBYHR_T015-LGART .
      SELECT SINGLE * FROM T512T WHERE
MOLGA = T512W-MOLGA AND
LGART = T512W-LGART AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZBYHR_V015-LGTXT =
T512T-LGTXT .
      ENDIF.
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = ZBYHR_V015.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZBYHR_V015 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZBYHR_V015.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZBYHR_V015-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T015 WHERE
  SEQNO = ZBYHR_V015-SEQNO AND
  ANAGR = ZBYHR_V015-ANAGR AND
  ALTGR = ZBYHR_V015-ALTGR AND
  SLGA = ZBYHR_V015-SLGA AND
  LGART = ZBYHR_V015-LGART .
    IF SY-SUBRC = 0.
    DELETE ZBYHR_T015 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T015 WHERE
  SEQNO = ZBYHR_V015-SEQNO AND
  ANAGR = ZBYHR_V015-ANAGR AND
  ALTGR = ZBYHR_V015-ALTGR AND
  SLGA = ZBYHR_V015-SLGA AND
  LGART = ZBYHR_V015-LGART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZBYHR_T015.
    ENDIF.
ZBYHR_T015-MANDT =
ZBYHR_V015-MANDT .
ZBYHR_T015-SEQNO =
ZBYHR_V015-SEQNO .
ZBYHR_T015-ANAGR =
ZBYHR_V015-ANAGR .
ZBYHR_T015-ALTGR =
ZBYHR_V015-ALTGR .
ZBYHR_T015-SLGA =
ZBYHR_V015-SLGA .
ZBYHR_T015-LGART =
ZBYHR_V015-LGART .
ZBYHR_T015-PERSK =
ZBYHR_V015-PERSK .
ZBYHR_T015-SSGRP =
ZBYHR_V015-SSGRP .
ZBYHR_T015-SIRAN =
ZBYHR_V015-SIRAN .
ZBYHR_T015-DESCR =
ZBYHR_V015-DESCR .
ZBYHR_T015-PDATE =
ZBYHR_V015-PDATE .
ZBYHR_T015-PHOUR =
ZBYHR_V015-PHOUR .
ZBYHR_T015-SUMWT =
ZBYHR_V015-SUMWT .
ZBYHR_T015-PERSON =
ZBYHR_V015-PERSON .
    IF SY-SUBRC = 0.
    UPDATE ZBYHR_T015 ##WARN_OK.
    ELSE.
    INSERT ZBYHR_T015 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZBYHR_V015-UPD_FLAG,
STATUS_ZBYHR_V015-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZBYHR_V015.
  SELECT SINGLE * FROM ZBYHR_T015 WHERE
SEQNO = ZBYHR_V015-SEQNO AND
ANAGR = ZBYHR_V015-ANAGR AND
ALTGR = ZBYHR_V015-ALTGR AND
SLGA = ZBYHR_V015-SLGA AND
LGART = ZBYHR_V015-LGART .
ZBYHR_V015-MANDT =
ZBYHR_T015-MANDT .
ZBYHR_V015-SEQNO =
ZBYHR_T015-SEQNO .
ZBYHR_V015-ANAGR =
ZBYHR_T015-ANAGR .
ZBYHR_V015-ALTGR =
ZBYHR_T015-ALTGR .
ZBYHR_V015-SLGA =
ZBYHR_T015-SLGA .
ZBYHR_V015-LGART =
ZBYHR_T015-LGART .
ZBYHR_V015-PERSK =
ZBYHR_T015-PERSK .
ZBYHR_V015-SSGRP =
ZBYHR_T015-SSGRP .
ZBYHR_V015-SIRAN =
ZBYHR_T015-SIRAN .
ZBYHR_V015-DESCR =
ZBYHR_T015-DESCR .
ZBYHR_V015-PDATE =
ZBYHR_T015-PDATE .
ZBYHR_V015-PHOUR =
ZBYHR_T015-PHOUR .
ZBYHR_V015-SUMWT =
ZBYHR_T015-SUMWT .
ZBYHR_V015-PERSON =
ZBYHR_T015-PERSON .
    SELECT SINGLE * FROM ZBYHR_T014 WHERE
SEQNO = ZBYHR_T015-SEQNO AND
ANAGR = ZBYHR_T015-ANAGR AND
ALTGR = ZBYHR_T015-ALTGR AND
SLGA = ZBYHR_T015-SLGA .
    IF SY-SUBRC EQ 0.
ZBYHR_V015-SLGA_T =
ZBYHR_T014-LGTXT .
      SELECT SINGLE * FROM ZBYHR_T013 WHERE
SEQNO = ZBYHR_T014-SEQNO AND
ANAGR = ZBYHR_T014-ANAGR AND
ALTGR = ZBYHR_T014-ALTGR .
      IF SY-SUBRC EQ 0.
ZBYHR_V015-ALTGR_T =
ZBYHR_T013-DESCR .
        SELECT SINGLE * FROM ZBYHR_T012 WHERE
SEQNO = ZBYHR_T013-SEQNO AND
ANAGR = ZBYHR_T013-ANAGR .
        IF SY-SUBRC EQ 0.
ZBYHR_V015-ANAGR_T =
ZBYHR_T012-DESCR .
        ELSE.
          CLEAR SY-SUBRC.
          CLEAR ZBYHR_V015-ANAGR_T .
        ENDIF.
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZBYHR_V015-ALTGR_T .
        CLEAR ZBYHR_V015-ANAGR_T .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V015-SLGA_T .
      CLEAR ZBYHR_V015-ANAGR_T .
      CLEAR ZBYHR_V015-ALTGR_T .
    ENDIF.
    SELECT * FROM T512W WHERE
MOLGA = '47' AND
LGART = ZBYHR_T015-LGART .
      SELECT SINGLE * FROM T512T WHERE
MOLGA = T512W-MOLGA AND
LGART = T512W-LGART AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZBYHR_V015-LGTXT =
T512T-LGTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZBYHR_V015-LGTXT .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V015-LGTXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZBYHR_V015 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZBYHR_V015-SEQNO TO
ZBYHR_T015-SEQNO .
MOVE ZBYHR_V015-ANAGR TO
ZBYHR_T015-ANAGR .
MOVE ZBYHR_V015-ALTGR TO
ZBYHR_T015-ALTGR .
MOVE ZBYHR_V015-SLGA TO
ZBYHR_T015-SLGA .
MOVE ZBYHR_V015-LGART TO
ZBYHR_T015-LGART .
MOVE ZBYHR_V015-MANDT TO
ZBYHR_T015-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZBYHR_T015'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZBYHR_T015 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZBYHR_T015'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZBYHR_V015 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZBYHR_T015-MANDT =
ZBYHR_V015-MANDT .
ZBYHR_T015-SEQNO =
ZBYHR_V015-SEQNO .
ZBYHR_T015-ANAGR =
ZBYHR_V015-ANAGR .
ZBYHR_T015-ALTGR =
ZBYHR_V015-ALTGR .
ZBYHR_T015-SLGA =
ZBYHR_V015-SLGA .
ZBYHR_T015-LGART =
ZBYHR_V015-LGART .
ZBYHR_T015-PERSK =
ZBYHR_V015-PERSK .
ZBYHR_T015-SSGRP =
ZBYHR_V015-SSGRP .
ZBYHR_T015-SIRAN =
ZBYHR_V015-SIRAN .
ZBYHR_T015-DESCR =
ZBYHR_V015-DESCR .
ZBYHR_T015-PDATE =
ZBYHR_V015-PDATE .
ZBYHR_T015-PHOUR =
ZBYHR_V015-PHOUR .
ZBYHR_T015-SUMWT =
ZBYHR_V015-SUMWT .
ZBYHR_T015-PERSON =
ZBYHR_V015-PERSON .
    SELECT SINGLE * FROM ZBYHR_T014 WHERE
SEQNO = ZBYHR_T015-SEQNO AND
ANAGR = ZBYHR_T015-ANAGR AND
ALTGR = ZBYHR_T015-ALTGR AND
SLGA = ZBYHR_T015-SLGA .
    IF SY-SUBRC EQ 0.
ZBYHR_V015-SLGA_T =
ZBYHR_T014-LGTXT .
      SELECT SINGLE * FROM ZBYHR_T013 WHERE
SEQNO = ZBYHR_T014-SEQNO AND
ANAGR = ZBYHR_T014-ANAGR AND
ALTGR = ZBYHR_T014-ALTGR .
      IF SY-SUBRC EQ 0.
ZBYHR_V015-ALTGR_T =
ZBYHR_T013-DESCR .
        SELECT SINGLE * FROM ZBYHR_T012 WHERE
SEQNO = ZBYHR_T013-SEQNO AND
ANAGR = ZBYHR_T013-ANAGR .
        IF SY-SUBRC EQ 0.
ZBYHR_V015-ANAGR_T =
ZBYHR_T012-DESCR .
        ELSE.
          CLEAR SY-SUBRC.
          CLEAR ZBYHR_V015-ANAGR_T .
        ENDIF.
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZBYHR_V015-ALTGR_T .
        CLEAR ZBYHR_V015-ANAGR_T .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V015-SLGA_T .
      CLEAR ZBYHR_V015-ANAGR_T .
      CLEAR ZBYHR_V015-ALTGR_T .
    ENDIF.
    SELECT * FROM T512W WHERE
MOLGA = '47' AND
LGART = ZBYHR_T015-LGART .
      SELECT SINGLE * FROM T512T WHERE
MOLGA = T512W-MOLGA AND
LGART = T512W-LGART AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZBYHR_V015-LGTXT =
T512T-LGTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZBYHR_V015-LGTXT .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZBYHR_V015-LGTXT .
    ENDIF.
ENDFORM.
*...processing: ZBYHR_V018......................................*
FORM GET_DATA_ZBYHR_V018.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZBYHR_T018 WHERE
(VIM_WHERETAB) .
    CLEAR ZBYHR_V018 .
ZBYHR_V018-MANDT =
ZBYHR_T018-MANDT .
ZBYHR_V018-PERID =
ZBYHR_T018-PERID .
ZBYHR_V018-LGART =
ZBYHR_T018-LGART .
    SELECT * FROM ZBYHR_T017 WHERE
PERID = ZBYHR_T018-PERID .
      EXIT.
    ENDSELECT.
    SELECT * FROM ZBYHR_T014 WHERE
SLGA = ZBYHR_T018-LGART .
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = ZBYHR_V018.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZBYHR_V018 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZBYHR_V018.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZBYHR_V018-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T018 WHERE
  PERID = ZBYHR_V018-PERID AND
  LGART = ZBYHR_V018-LGART .
    IF SY-SUBRC = 0.
    DELETE ZBYHR_T018 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZBYHR_T018 WHERE
  PERID = ZBYHR_V018-PERID AND
  LGART = ZBYHR_V018-LGART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZBYHR_T018.
    ENDIF.
ZBYHR_T018-MANDT =
ZBYHR_V018-MANDT .
ZBYHR_T018-PERID =
ZBYHR_V018-PERID .
ZBYHR_T018-LGART =
ZBYHR_V018-LGART .
    IF SY-SUBRC = 0.
    UPDATE ZBYHR_T018 ##WARN_OK.
    ELSE.
    INSERT ZBYHR_T018 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZBYHR_V018-UPD_FLAG,
STATUS_ZBYHR_V018-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZBYHR_V018.
  SELECT SINGLE * FROM ZBYHR_T018 WHERE
PERID = ZBYHR_V018-PERID AND
LGART = ZBYHR_V018-LGART .
ZBYHR_V018-MANDT =
ZBYHR_T018-MANDT .
ZBYHR_V018-PERID =
ZBYHR_T018-PERID .
ZBYHR_V018-LGART =
ZBYHR_T018-LGART .
    SELECT * FROM ZBYHR_T017 WHERE
PERID = ZBYHR_T018-PERID .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT * FROM ZBYHR_T014 WHERE
SLGA = ZBYHR_T018-LGART .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZBYHR_V018 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZBYHR_V018-PERID TO
ZBYHR_T018-PERID .
MOVE ZBYHR_V018-LGART TO
ZBYHR_T018-LGART .
MOVE ZBYHR_V018-MANDT TO
ZBYHR_T018-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZBYHR_T018'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZBYHR_T018 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZBYHR_T018'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZBYHR_V018 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZBYHR_T018-MANDT =
ZBYHR_V018-MANDT .
ZBYHR_T018-PERID =
ZBYHR_V018-PERID .
ZBYHR_T018-LGART =
ZBYHR_V018-LGART .
    SELECT * FROM ZBYHR_T017 WHERE
PERID = ZBYHR_T018-PERID .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT * FROM ZBYHR_T014 WHERE
SLGA = ZBYHR_T018-LGART .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
