PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBYHR_V015 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBYHR_V015-LGART .
    FIELD ZBYHR_V015-LGTXT .
    FIELD ZBYHR_V015-PERSK .
    FIELD ZBYHR_V015-SSGRP .
    FIELD ZBYHR_V015-SIRAN .
    FIELD ZBYHR_V015-DESCR .
    FIELD ZBYHR_V015-PDATE .
    FIELD ZBYHR_V015-PHOUR .
    FIELD ZBYHR_V015-SUMWT .
    FIELD ZBYHR_V015-PERSON .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZBYHR_V015 ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBYHR_V015-LGART .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
