PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBYHR_T003 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBYHR_T003-SPRSL .
    FIELD ZBYHR_T003-PROGNAME .
    FIELD ZBYHR_T003-BUKRS .
    FIELD ZBYHR_T003-T_LGART .
    FIELD ZBYHR_T003-LGTXT .
    FIELD ZBYHR_T003-SUMSIGN .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBYHR_T003-SPRSL .
    FIELD ZBYHR_T003-PROGNAME .
    FIELD ZBYHR_T003-BUKRS .
    FIELD ZBYHR_T003-T_LGART .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
