*&---------------------------------------------------------------------*
*& Include          ZHRPAINC_SECIMLER
*&---------------------------------------------------------------------*
*----------------------------------------------------------------------*
*   INCLUDE ZHRPAINC_SECIMLER                                          *
*----------------------------------------------------------------------*
*tables: t001.
DATA : ILK_TARIH(10),
       SON_TARIH(10).
DATA : SIRKET(40)       VALUE 'Şirket :',
       DONEM(40)        VALUE 'Dönem        :',
       PERSONEL(40)     VALUE 'Personel         :',
       PERSALANI(40)    VALUE 'Personel alanı   :',
       PALTALANI(40)    VALUE 'Personel altalanı:',
       CALGRUBU(40)     VALUE 'Çalışan grubu    :',
       CALALTGRB(40)    VALUE 'Çalışan alt grubu:',
       BDRALTBIRIMI(40) VALUE 'Bordro alt birimi:',
       ORGANIZASYON(40) VALUE 'Orgnzasyon birimi:',
       USTALAN(40)      VALUE 'Üstalan(Şefalanı):'.
*** 'Şirket :' ***
IF PNPBUKRS-LOW IS INITIAL.
ELSEIF PNPBUKRS-HIGH IS INITIAL.
  SELECT * FROM T001 WHERE BUKRS = PNPBUKRS-LOW.
  ENDSELECT.
  IF PNPBUKRS-OPTION EQ 'EQ'.
    CONCATENATE SIRKET T001-BUTXT
                INTO SIRKET SEPARATED BY SPACE.
  ELSEIF PNPBUKRS-OPTION EQ 'NE'.
    CONCATENATE SIRKET T001-BUTXT '-HARİCİ-'
                INTO SIRKET SEPARATED BY SPACE.
  ELSE.
    CONCATENATE SIRKET '(' PNPBUKRS-OPTION ')' T001-BUTXT
                INTO SIRKET SEPARATED BY SPACE.
  ENDIF.
ELSE.
  CONCATENATE SIRKET PNPBUKRS-LOW '-' PNPBUKRS-HIGH
              INTO SIRKET SEPARATED BY SPACE.
ENDIF.
*** 'Dönem :' ***
WRITE PN-BEGDA TO ILK_TARIH DD/MM/YYYY.
WRITE PN-ENDDA TO SON_TARIH DD/MM/YYYY.
CONCATENATE DONEM ILK_TARIH '-' SON_TARIH
            INTO DONEM SEPARATED BY SPACE.
*** 'Personel :' ***
IF PNPPERNR-LOW IS INITIAL.
ELSEIF PNPPERNR-HIGH IS INITIAL.
  IF PNPPERNR-OPTION EQ 'EQ'.
    CONCATENATE PERSONEL PNPPERNR-LOW
                INTO PERSONEL SEPARATED BY SPACE.
  ELSEIF PNPPERNR-OPTION EQ 'NE'.
    CONCATENATE PERSONEL PNPPERNR-LOW '-HARİCİ-'
                INTO PERSONEL SEPARATED BY SPACE.
  ELSE.
    CONCATENATE PERSONEL '(' PNPPERNR-OPTION ')' PNPPERNR-LOW
                INTO PERSONEL SEPARATED BY SPACE.
  ENDIF.
ELSE.
  CONCATENATE PERSONEL PNPPERNR-LOW '-' PNPPERNR-HIGH
              INTO PERSONEL SEPARATED BY SPACE.
ENDIF.
*** 'Personel alanı :' ***
IF PNPWERKS-LOW IS INITIAL.
ELSEIF PNPWERKS-HIGH IS INITIAL.
  IF PNPWERKS-OPTION EQ 'EQ'.
    CONCATENATE PERSALANI PNPWERKS-LOW
                INTO PERSALANI SEPARATED BY SPACE.
  ELSEIF PNPWERKS-OPTION EQ 'NE'.
    CONCATENATE PERSALANI PNPWERKS-LOW '-HARİCİ-'
                INTO PERSALANI SEPARATED BY SPACE.
  ELSE.
    CONCATENATE PERSALANI '(' PNPWERKS-OPTION ')' PNPWERKS-LOW
                INTO PERSALANI SEPARATED BY SPACE.
  ENDIF.
ELSE.
  CONCATENATE PERSALANI PNPWERKS-LOW '-' PNPWERKS-HIGH
              INTO PERSALANI SEPARATED BY SPACE.
ENDIF.
*** 'Personel alt alanı :' ***
IF PNPBTRTL-LOW IS INITIAL.
ELSEIF PNPBTRTL-HIGH IS INITIAL.
  IF PNPBTRTL-OPTION EQ 'EQ'.
    CONCATENATE PALTALANI PNPBTRTL-LOW
                INTO PALTALANI SEPARATED BY SPACE.
  ELSEIF PNPBTRTL-OPTION EQ 'NE'.
    CONCATENATE PALTALANI PNPBTRTL-LOW '-HARİCİ-'
                INTO PALTALANI SEPARATED BY SPACE.
  ELSE.
    CONCATENATE PALTALANI '(' PNPBTRTL-OPTION ')' PNPBTRTL-LOW
                INTO PALTALANI SEPARATED BY SPACE.
  ENDIF.
ELSE.
  CONCATENATE PALTALANI PNPBTRTL-LOW '-' PNPBTRTL-HIGH
              INTO PALTALANI SEPARATED BY SPACE.
ENDIF.
*** 'Çalışan grubu :' ***
IF PNPPERSG-LOW IS INITIAL.
ELSEIF PNPPERSG-HIGH IS INITIAL.
  IF PNPPERSG-OPTION EQ 'EQ'.
    CONCATENATE CALGRUBU PNPPERSG-LOW
                INTO CALGRUBU SEPARATED BY SPACE.
  ELSEIF PNPPERSG-OPTION EQ 'NE'.
    CONCATENATE CALGRUBU PNPPERSG-LOW '-HARİCİ-'
                INTO CALGRUBU SEPARATED BY SPACE.
  ELSE.
    CONCATENATE CALGRUBU '(' PNPPERSG-OPTION ')' PNPPERSG-LOW
                INTO CALGRUBU SEPARATED BY SPACE.
  ENDIF.
ELSE.
  CONCATENATE CALGRUBU PNPPERSG-LOW '-' PNPPERSG-HIGH
              INTO CALGRUBU SEPARATED BY SPACE.
ENDIF.
*** 'Çalışan alt grubu :' ***
IF PNPPERSK-LOW IS INITIAL.
ELSEIF PNPPERSK-HIGH IS INITIAL.
  IF PNPPERSK-OPTION EQ 'EQ'.
    CONCATENATE CALALTGRB PNPPERSK-LOW
                INTO CALALTGRB SEPARATED BY SPACE.
  ELSEIF PNPPERSK-OPTION EQ 'NE'.
    CONCATENATE CALALTGRB PNPPERSK-LOW '-HARİCİ-'
                INTO CALALTGRB SEPARATED BY SPACE.
  ELSE.
    CONCATENATE CALALTGRB '(' PNPPERSK-OPTION ')' PNPPERSK-LOW
                INTO CALALTGRB SEPARATED BY SPACE.
  ENDIF.
ELSE.
  CONCATENATE CALALTGRB PNPPERSK-LOW '-' PNPPERSK-HIGH
              INTO CALALTGRB SEPARATED BY SPACE.
ENDIF.
*** 'Bordro alt birimi :' ***
IF PNPABKRS-LOW IS INITIAL.
ELSEIF PNPABKRS-HIGH IS INITIAL.
  IF PNPABKRS-OPTION EQ 'EQ'.
    CONCATENATE BDRALTBIRIMI PNPABKRS-LOW
                INTO BDRALTBIRIMI SEPARATED BY SPACE.
  ELSEIF PNPABKRS-OPTION EQ 'NE'.
    CONCATENATE BDRALTBIRIMI PNPABKRS-LOW '-HARİCİ-'
                INTO BDRALTBIRIMI SEPARATED BY SPACE.
  ELSE.
    CONCATENATE BDRALTBIRIMI '(' PNPABKRS-OPTION ')' PNPABKRS-LOW
                INTO BDRALTBIRIMI SEPARATED BY SPACE.
  ENDIF.
ELSE.
  CONCATENATE BDRALTBIRIMI PNPABKRS-LOW '-' PNPABKRS-HIGH
              INTO BDRALTBIRIMI SEPARATED BY SPACE.
ENDIF.
*** 'Organizasyon birimi :' ***
IF PNPORGEH-LOW IS INITIAL.
ELSEIF PNPORGEH-HIGH IS INITIAL.
  IF PNPORGEH-OPTION EQ 'EQ'.
    CONCATENATE ORGANIZASYON PNPORGEH-LOW
                INTO ORGANIZASYON SEPARATED BY SPACE.
  ELSEIF PNPORGEH-OPTION EQ 'NE'.
    CONCATENATE ORGANIZASYON PNPORGEH-LOW '-HARİCİ-'
                INTO ORGANIZASYON SEPARATED BY SPACE.
  ELSE.
    CONCATENATE ORGANIZASYON '(' PNPORGEH-OPTION ')' PNPORGEH-LOW
                INTO ORGANIZASYON SEPARATED BY SPACE.
  ENDIF.
ELSE.
  CONCATENATE ORGANIZASYON PNPORGEH-LOW '-' PNPORGEH-HIGH
              INTO ORGANIZASYON SEPARATED BY SPACE.
ENDIF.
*** 'Üst alan (Şef alanı) :' ***
IF PNPMSTBR-LOW IS INITIAL.
ELSEIF PNPMSTBR-HIGH IS INITIAL.
  IF PNPMSTBR-OPTION EQ 'EQ'.
    CONCATENATE USTALAN PNPMSTBR-LOW
                INTO USTALAN SEPARATED BY SPACE.
  ELSEIF PNPMSTBR-OPTION EQ 'NE'.
    CONCATENATE USTALAN PNPMSTBR-LOW '-HARİCİ-'
                INTO USTALAN SEPARATED BY SPACE.
  ELSE.
    CONCATENATE USTALAN '(' PNPMSTBR-OPTION ')' PNPMSTBR-LOW
                INTO USTALAN SEPARATED BY SPACE.
  ENDIF.
ELSE.
  CONCATENATE USTALAN PNPMSTBR-LOW '-' PNPMSTBR-HIGH
              INTO USTALAN SEPARATED BY SPACE.
ENDIF.
