*
PROCESS BEFORE OUTPUT.
  MODULE MODIFY_SUBSCREEN.
  MODULE MODULE_PBO_0001.
  MODULE HIDDEN_DATA_SUBSCREEN.
*
PROCESS AFTER INPUT.
*   This chain has to include all input-fields:
  CHAIN.
    FIELD P0001-ZZDPRT.
    FIELD P0001-ZZPESNFK.
    FIELD P0001-ZZPERSNF.
    FIELD P0001-ZZSTSBK.
    FIELD P0001-ZZSTSB.
    FIELD P0001-ZZLVLK.
    FIELD P0001-ZZLVL.
    FIELD P0001-ZZDGTMKD.
    FIELD P0001-ZZDGTM.
    MODULE INPUT_STATUS_SUBSCREEN ON CHAIN-REQUEST.
  ENDCHAIN.
*   infotype specific checks etc.:
  MODULE MODULE_PAI_0001.
